### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by Straight12** [Rdimo/DiscordRAT#19]
Requirement already satisfied: discord==1.7.3 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (1.7.3)
Collecting discord-components==2.1.2
  Using cached discord_components-2.1.2-py3-none-any.whl (13 kB)
Collecting discord-py-slash-command==3.0.3
  Using cached discord_py_slash_command-3.0.3-py3-none-any.whl (45 kB)
Requirement already satisfied: pyinstaller in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (4.10)
Requirement already satisfied: requests in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (2.27.1)
Requirement already satisfied: asyncio in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (3.4.3)
Requirement already satisfied: mss in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (6.1.0)
Requirement already satisfied: pyautogui in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (0.9.53)
Requirement already satisfied: pynput in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (1.7.6)
Requirement already satisfied: pycaw in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (20181226)
Requirement already satisfied: comtypes in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (1.1.11)
Requirement already satisfied: pypiwin32 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 12)) (223)
Requirement already satisfied: opencv-python in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 13)) (4.5.5.62)
Requirement already satisfied: discord.py>=1.7.3 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from discord==1.7.3->-r requirements.txt (line 1)) (1.7.3)
Requirement already satisfied: aiohttp in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from discord-components==2.1.2->-r requirements.txt (line 2)) (3.7.4.post0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 4)) (2022.2)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 4)) (2021.9.3)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: setuptools in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 4)) (58.1.0)
Requirement already satisfied: altgraph in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 4)) (0.17.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (2.0.12)
Requirement already satisfied: pymsgbox in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 8)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 8)) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 8)) (0.1.28)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 8)) (0.0.9)
Requirement already satisfied: mouseinfo in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 8)) (0.1.3)
Requirement already satisfied: six in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pynput->-r requirements.txt (line 9)) (1.16.0)
Collecting enum34
  Using cached enum34-1.1.10-py3-none-any.whl (11 kB)
Requirement already satisfied: psutil in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pycaw->-r requirements.txt (line 10)) (5.9.0)
Requirement already satisfied: future in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pycaw->-r requirements.txt (line 10)) (0.18.2)
Requirement already satisfied: pywin32>=223 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pypiwin32->-r requirements.txt (line 12)) (303)
Requirement already satisfied: numpy>=1.14.5 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from opencv-python->-r requirements.txt (line 13)) (1.22.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (6.0.2)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (4.1.1)
Requirement already satisfied: chardet<5.0,>=2.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->discord-components==2.1.2->-r requirements.txt (line 2)) (21.4.0)
Requirement already satisfied: pyrect in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from pygetwindow>=0.0.5->pyautogui->-r requirements.txt (line 8)) (0.1.4)
Requirement already satisfied: pyperclip in c:\users\tomer\appdata\local\programs\python\python310\lib\site-packages (from mouseinfo->pyautogui->-r requirements.txt (line 8)) (1.8.2)
Installing collected packages: enum34, discord-py-slash-command, discord-components
Successfully installed discord-components-2.1.2 discord-py-slash-command-3.0.3 enum34-1.1.10

C:\Users\tomer\OneDrive\Documents\projects\github\DiscordRAT>main.py
Traceback (most recent call last):
  File "C:\Users\tomer\OneDrive\Documents\projects\github\DiscordRAT\main.py", line 589, in <module>
    client.run(token)
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002B9AC3FACB0>
Traceback (most recent call last):
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\tomer\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Rdimo** [comment]
what the fuck

**Comment by Python1001dz** [comment]
1- add this to the top of the script maine.py
import platform
if platform.system()=='Windows':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
 
2- save and run again
